Repository BinaryStudioAcademy/bsa-2023-leetwars, pull requests merged in 2023-09, with the labels that each got.

#76 fixed autofill input caret color
  frontend/src/styles/global.sass
Labels: bug

#82 bug 20 main page design
  frontend/src/app/modules/main/challenge/challenge.component.sass
  frontend/src/app/modules/main/filtering-section/filtering-section.component.sass
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/styles/bootstrap-variables.sass
Labels: bug

#81 Improvement/refactor-error-messages-display
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/validation/form-control-validator-options.ts
  frontend/src/app/shared/utils/validation/form-controls-error-messages.ts
  frontend/src/app/shared/utils/validation/regex-patterns.ts
  frontend/src/app/shared/utils/validation/validation-helper.ts
  frontend/src/app/shared/utils/validation/validation-interfaces.ts
Labels: bug, enhancement

#88 added email input maxlength validation
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/validation/form-control-validator-options.ts
  frontend/src/app/shared/utils/validation/form-controls-error-messages.ts
Labels: bug

#86 Change sign up button radius
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
Labels: bug

#83 bug/21-landing-page
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
Labels: bug

#89 Hotfix/23 validate email domain part
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/validation/form-controls-error-messages.ts
  frontend/src/app/shared/utils/validation/regex-patterns.ts
  frontend/src/app/shared/utils/validation/validation-helper.ts
Labels: bug

#91 bug/27 unauthorized access
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/guards/authorized.guard.ts
  frontend/src/app/core/guards/unauthorized.guard.ts
Labels: bug

#92 Fix signup redirection issue
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/validation/email-exists.validator.ts
  frontend/src/app/shared/utils/validation/username-exists.validator.ts
Labels: bug

#96 bug 33 challenge component is absent
  frontend/src/app/modules/main/filtering-section/filtering-section.component.html
  frontend/src/app/modules/main/filtering-section/filtering-section.component.sass
Labels: bug

#97 fixed design problems with editor page
  frontend/src/app/modules/challenges/editor-question/editor-question.component.sass
  frontend/src/styles/color-variables.sass
Labels: bug

#93 Fix spaces in signIn and signUp
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/shared/utils/validation/regex-patterns.ts
Labels: bug

#98 refactored code, added adaptive styles
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/styles/bootstrap-variables.sass
  frontend/src/styles/global.sass
Labels: bug

#95 Bug/36 selected tag is all
  frontend/src/app/modules/challenges/challenges-dropdown-select/challenges-dropdown-select.component.ts
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.html
  frontend/src/app/modules/challenges/editor-question/editor-question.component.sass
  frontend/src/app/modules/challenges/solution-page/solution-page.component.html
  frontend/src/app/modules/main/filtering-section/filtering-section.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/online-editor/online-editor-page/online-editor-page.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
Labels: bug

#99 Add enum to string serialization
  backend/LeetWars.Core/LeetWars.Core.DAL/Enums/Country.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
  frontend/src/app/shared/enums/category-type.ts
  frontend/src/app/shared/enums/challenge-progress.ts
  frontend/src/app/shared/enums/challenge-status.ts
  frontend/src/app/shared/enums/country.ts
  frontend/src/app/shared/enums/sex.ts
  frontend/src/app/shared/enums/suggestion-type.ts
  frontend/src/app/shared/enums/tab-type.ts
  frontend/src/app/shared/enums/userStatus.ts
Labels: enhancement

#101 refactored code, improved adaptive design
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.sass
  frontend/src/app/modules/main/filtering-section/filtering-section.component.sass
  frontend/src/styles/screen-sizes-variables.sass
Labels: bug

#100 fixed showing mistakes with firebase
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
Labels: bug

#102 fixed programming language icons
  frontend/src/app/shared/utils/language-icons.ts
  frontend/src/assets/images/programming-languages/csharp.png
  frontend/src/assets/images/programming-languages/default_pl.png
  frontend/src/assets/images/programming-languages/html.png
  frontend/src/assets/images/programming-languages/js.png
  frontend/src/assets/images/programming-languages/python.png
  frontend/src/assets/images/programming-languages/ruby.png
  frontend/src/assets/images/programming-languages/ts.png
Labels: bug

#103 Feature/username validation improvement
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Regaxes/RegexPatterns.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/User/UserRegisterDTOValidator.cs
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/validation/form-controls-error-messages.ts
  frontend/src/app/shared/utils/validation/regex-patterns.ts
Labels: enhancement

#104 rework routing
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/guards/authorized.guard.ts
  frontend/src/app/core/guards/unauthorized.guard.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
Labels: enhancement

#109 fixed spaces for username
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Regaxes/RegexPatterns.cs
  frontend/src/app/shared/utils/validation/regex-patterns.ts
Labels: bug

#113 fixed display for multiselect dropdown
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
Labels: bug

#80 bugfix/17-header-is-absent
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/core/guards/hide-header.guard.ts
  frontend/src/app/core/services/header-service.ts
Labels: bug

#111 bug/127 like challenge
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/ChallengeProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.ts
  frontend/src/app/shared/models/challenge/challenge-preview.ts
Labels: bug

#124 Bug/48 landing nav section design fix
  frontend/src/app/core/directives/scroll-to.directive.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/landing/landing.module.ts
Labels: bug

#119 fixed header when login
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/guards/header.guard.ts
  frontend/src/app/core/services/header-service.ts
Labels: bug

#122 fixed message when entering wrong login
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
Labels: bug, enhancement

#112 Feature/125 welcome letter
  backend/LeetWars.Core/LeetWars.Core.BLL/Helpers/Email/EmailGenerator.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Mail/MailDto.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Emailer/Dockerfile
  backend/LeetWars.Emailer/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Emailer/Interfaces/IMailService.cs
  backend/LeetWars.Emailer/LeetWars.Emailer.csproj
  backend/LeetWars.Emailer/Program.cs
  backend/LeetWars.Emailer/Properties/launchSettings.json
  backend/LeetWars.Emailer/Services/MailService.cs
  backend/LeetWars.Emailer/Services/MessageConsumerService.cs
  backend/LeetWars.Emailer/Validators/MailDtoValidator.cs
  backend/LeetWars.Emailer/appsettings.json
  docker-compose.apps.yml
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/utils/auth.helper.ts
Labels: enhancement

#120 Feature/145-real-data-in-header
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
Labels: enhancement

#125 Feature/35-create-challenge-page
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.html
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.html
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.ts
  frontend/src/app/modules/challenges/solution-page/solution-page.component.html
  frontend/src/app/modules/challenges/solution-page/solution-page.component.ts
  frontend/src/app/modules/challenges/styles/challenge-creation-code-editor.sass
Labels: bug

#138 Fix redirection issue
  frontend/src/app/core/services/auth.service.ts
Labels: bug

#134 Feature/144-reset password
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/login/change-password/change-password.component.html
  frontend/src/app/modules/login/change-password/change-password.component.sass
  frontend/src/app/modules/login/change-password/change-password.component.ts
  frontend/src/app/modules/login/forget-password/forget-password.component.html
  frontend/src/app/modules/login/forget-password/forget-password.component.sass
  frontend/src/app/modules/login/forget-password/forget-password.component.ts
  frontend/src/app/modules/login/log-in-routing.module.ts
  frontend/src/app/modules/login/log-in.module.ts
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/constants/user-management-constants.ts
  frontend/src/app/shared/utils/validation/compare.validator.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
Labels: enhancement

#139 Improvement/0 challenge and username
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.sass
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/styles/color-variables.sass
Labels: bug, enhancement

#135 fixed spaces in username
  frontend/src/app/modules/main/filtering-section/filtering-section.component.ts
Labels: bug

#132 Feature/133 code analysis
  README.md
  backend/LeetWars.All.sln
  backend/LeetWars.CodeAnalyzer/Dockerfile
  backend/LeetWars.CodeAnalyzer/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.CodeAnalyzer/Interfaces/IAnalyzeCodeService.cs
  backend/LeetWars.CodeAnalyzer/Interfaces/ICompletionService.cs
  backend/LeetWars.CodeAnalyzer/Interfaces/IOpenAiSettings.cs
  backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.csproj
  backend/LeetWars.CodeAnalyzer/OpenAISettings/OpenAiSettings.cs
  backend/LeetWars.CodeAnalyzer/Program.cs
  backend/LeetWars.CodeAnalyzer/Properties/launchSettings.json
  backend/LeetWars.CodeAnalyzer/Services/AnalyzeCodeService.cs
  backend/LeetWars.CodeAnalyzer/Services/CompletionService.cs
  backend/LeetWars.CodeAnalyzer/appsettings.Development.json
  backend/LeetWars.CodeAnalyzer/appsettings.json
  backend/LeetWars.Core/LeetWars.Core.BLL/LeetWars.Core.BLL.csproj
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeAnalysis/CodeRequestAnalysisDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeAnalysis/CodeResponseAnalysisDto.cs
  docker-compose.apps.prod.yml
  docker-compose.apps.yml
  frontend/nginx.conf
Labels: enhancement

#130 feature/143-log-out
  frontend/src/app/shared/components/confirmation-modal/confirmation-modal.component.html
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
Labels: enhancement, conflicts

#147 Change-volume-declaration
  docker-compose.apps.prod.yml
  docker-compose.apps.yml
Labels: bug

#148 fixed routerlink, added disabled when no challenge
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.ts
Labels: bug

#149 fixed colors for reset password
  frontend/src/app/modules/login/forget-password/forget-password.component.sass
Labels: bug, enhancement

#143 Improvement/5 create challenge
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.html
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.sass
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.html
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.sass
  frontend/src/app/modules/challenges/editor-question/editor-question.component.html
  frontend/src/app/modules/challenges/editor-question/editor-question.component.sass
  frontend/src/app/modules/challenges/solution-page/solution-page.component.html
  frontend/src/app/modules/challenges/solution-page/solution-page.component.sass
  frontend/src/app/modules/challenges/steps-of-progress/steps-of-progress.component.sass
  frontend/src/app/modules/challenges/styles/challenge-creation-code-editor.sass
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/styles/screen-sizes-variables.sass
  frontend/src/styles/tab.sass
Labels: bug, enhancement, conflicts

#145 fixed multiple languages, versions problem
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
Labels: bug

#154 fixed header styles, added adaptive
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
Labels: bug

#170 fixed editor opening in full screen [create challenge page]
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.html
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.sass
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.ts
Labels: bug

#171 creation-wrapper adapted
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.sass
Labels: bug

#158 extra scrolling is hidden in the description and solution blocks
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.sass
Labels: bug

#160 Feature/124 error interceptor
  backend/LeetWars.CodeAnalyzer/Services/AnalyzeCodeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/NewUserDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/AccessDeniedException.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/InvalidTokenException.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/InvalidUsernameOrPasswordException.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/NotFoundException.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Enums/ErrorCode.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ExceptionFilterExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Filters/CustomExceptionFilterAttribute.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Logic/UserStorage.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
  frontend/src/app/core/core.module.ts
  frontend/src/app/core/interceptors/error.interceptor.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/core/services/globalerrorhandler.service.ts
  frontend/src/app/core/services/http-internal.service.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/models/user/new-user.ts
  frontend/src/app/shared/utils/auth.helper.ts
  frontend/src/app/shared/utils/validation/form-controls-error-messages.ts
  frontend/src/app/shared/utils/validation/validation-helper.ts
Labels: enhancement

#164 Bug/74 jwt authorize
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeLevelController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/LanguageController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/TagsController.cs
Labels: bug

#169 fixed language icons and tags
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230919194457_UnifiedTagsAndLanguagesInChallenges.Designer.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230919194457_UnifiedTagsAndLanguagesInChallenges.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
Labels: bug

#172 fix login error
  frontend/src/app/core/services/auth.service.ts
Labels: bug

#167 Add user info editor page
  backend/LeetWars.Core/Dockerfile
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IBlobService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/Resolvers/UserAvatarResolver.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/UserProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/BlobService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/BlobStorageSettings.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/FileNameHelper.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/IDtoWithImage.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UpdateUserInfoDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserAvatarDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserFullDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/NotFoundException.cs
  backend/LeetWars.Core/LeetWars.Core.Common/LeetWars.Core.Common.csproj
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/appsettings.json
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.html
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.sass
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.ts
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.html
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.ts
  frontend/src/app/modules/user/user-routing.module.ts
  frontend/src/app/modules/user/user.module.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/constants/asset-constants.ts
  frontend/src/app/shared/models/user/edit-user-info.ts
  frontend/src/app/shared/models/user/user-avatar.ts
  frontend/src/app/shared/models/user/user.ts
  frontend/src/app/shared/utils/validation/file-validation-helper.ts
Labels: enhancement

#175 Disable email input
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.ts
Labels: bug

#185 bug/container-names-conflicts
  backend/LeetWars.Builder/Services/CodeRunManagerService.cs
Labels: bug

#184 Bugfix/rabbit queues
  backend/LeetWars.Builder/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Builder/Program.cs
  backend/LeetWars.Builder/Properties/launchSettings.json
  backend/LeetWars.Builder/appsettings.json
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IBuilderSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IEmailSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IMessageSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/INotitficationSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/UserProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/BuilderSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/EmailSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/MessageSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/NotificationSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Notifications/NewNotificationDto.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/User.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/appsettings.json
  backend/LeetWars.Emailer/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Emailer/appsettings.json
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Controllers/BroadcastController.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/BroadcastHub.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/CodeDisplayingHub.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/Interfaces/IBroadcastHubClient.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Program.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/MessageConsumerService.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/NotificationConsumerService.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/appsettings.json
  backend/LeetWars.RabbitMQ/Services/ConsumerService.cs
  backend/LeetWars.RabbitMQ/Services/GeneralConsumerService.cs
  backend/LeetWars.RabbitMQ/Services/NotifierCodeConsumerService.cs
  backend/LeetWars.RabbitMQ/Services/ProducerService.cs
  frontend/src/app/core/hubs/broadcast-hub.service.ts
  frontend/src/app/core/services/notification.service.ts
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
  frontend/src/app/modules/leader/leader-board/leader-board.component.ts
  frontend/src/app/modules/main/main-page/main-page.component.ts
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.html
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/components/notifications/notifications.component.ts
  frontend/src/app/shared/enums/type-notification.ts
  frontend/src/app/shared/models/notifications/notifications.ts
  frontend/src/styles/color-variables.sass
Labels: bug

#181 changed size for edit icon
  frontend/src/app/modules/main/challenge/challenge.component.html
Labels: bug

#182 Improvement/arrow up
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.ts
  frontend/src/app/modules/main/filtering-section/filtering-section.component.html
  frontend/src/app/modules/main/filtering-section/filtering-section.component.ts
  frontend/src/app/shared/components/arrow-up/arrow-up.component.html
  frontend/src/app/shared/components/arrow-up/arrow-up.component.sass
  frontend/src/app/shared/components/arrow-up/arrow-up.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/yarn.lock
Labels: bug, enhancement

#193 updated seed settings
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/SeedSettings/SeedDefaults.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230924205007_UpdateSeeding.Designer.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230924205007_UpdateSeeding.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
Labels: enhancement

#192 added app initialization service
  frontend/src/app/core/core.module.ts
  frontend/src/app/core/services/app-init.service.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
Labels: bug

#189 Fixed display of a problem when selecting “Select language...”
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Filters/SuggestionSettingsDto.cs
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.ts
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.utils.ts
  frontend/src/app/shared/models/challenge/suggestion-settings.ts
Labels: bug

#201 Improvement/bugfix/group of small bugs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Services/CodeRunManagerService.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Services/SolutionRunnerService.cs
  backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Program.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/ChallengeProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/LanguageProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Challenge/ChallengePreviewDto.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/ChallengeStarConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/ChallengeVersionConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/LanguageConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/LanguageVersionConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/LeetWarsCoreContext.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/ChallengeVersion.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/Language.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/LanguageVersion.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/User.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230927152001_DeleteLanguageVersions.Designer.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230927152001_DeleteLanguageVersions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
  frontend/src/app/modules/leader/leader-board/leader-board.component.ts
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.sass
  frontend/src/app/modules/main/challenge/challenge.component.ts
  frontend/src/app/modules/main/filtering-section/filtering-section.component.ts
  frontend/src/app/modules/main/filtering-section/filtering-section.utils.ts
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.html
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.sass
  frontend/src/app/shared/models/challenge-version/challenge-version.ts
  frontend/src/app/shared/models/challenge/challenge-preview.ts
  frontend/src/app/shared/models/language-version/language-version.ts
  frontend/src/app/shared/models/language/languageFull.ts
Labels: bug, enhancement

#187 Feature/180 friendships bis
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/Resolvers/FriendshipResolver.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/UserProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Filters/LeaderBoardPageSettingsDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Friendship/FriendshipPreviewDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Friendship/NewFriendshipDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Friendship/UpdateFriendshipDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Notifications/NewNotificationDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Notifications/TypeNotifications.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/UserFriendsInfoDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Exceptions/BadOperationException.cs
  backend/LeetWars.Core/LeetWars.Core.Common/Extensions/ExceptionFilterExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.Common/GlobalMiddlewares/GenericExceptionHandlerMiddleware.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/FriendshipConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/UserConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/UserFriendshipConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/LeetWarsCoreContext.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/SeedSettings/SeedDefaults.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/Friendship.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/User.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/UserFriendship.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Enums/ErrorCode.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Enums/FriendshipStatus.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230927155635_AddFriendship.Designer.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230927155635_AddFriendship.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Friendship/NewFriendshipDtoValidator.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Friendship/UpdateFriendshipDtoValidator.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/Interfaces/INotificationsHubClient.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/NotificationConsumerService.cs
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/event.service.ts
  frontend/src/app/core/services/notification.service.ts
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
  frontend/src/app/modules/leader/leader-board/leader-board.component.ts
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/components/notifications/notifications.component.sass
  frontend/src/app/shared/components/notifications/notifications.component.ts
  frontend/src/app/shared/enums/friendship-status.ts
  frontend/src/app/shared/enums/type-notification.ts
  frontend/src/app/shared/models/friendship/friendship-preview.ts
  frontend/src/app/shared/models/friendship/new-friendship.ts
  frontend/src/app/shared/models/friendship/update-friendship.ts
  frontend/src/app/shared/models/leaderboard-page-settings.ts
  frontend/src/app/shared/models/notifications/notifications.ts
  frontend/src/app/shared/models/user/user-friends-info.ts
  frontend/src/app/shared/models/user/user.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
Labels: enhancement

#197 Feature/200 connect GitHub account
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.html
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.ts
  frontend/src/app/shared/components/header/header.component.sass
Labels: enhancement

#205 fixed disabled dropdown, added validation
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/ChallengeProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Challenge/NewChallengeDto.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/ChallengeVersionConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230927152001_DeleteLanguageVersions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/ChallengeController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Challenge/EditChallengeDtoValidator.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Challenge/NewChallengeDtoValidator.cs
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.html
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
  frontend/src/app/modules/challenges/challenges-dropdown-select/challenges-dropdown-select.component.html
  frontend/src/app/modules/challenges/challenges-dropdown-select/challenges-dropdown-select.component.sass
  frontend/src/app/modules/challenges/challenges-dropdown-select/challenges-dropdown-select.component.ts
  frontend/src/app/shared/constants/second-constants.ts
Labels: bug

#204 Improvement/21 code fight notification
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Challenge/EditChallengeDtoValidator.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Challenge/NewChallengeDtoValidator.cs
  frontend/src/app/app.module.ts
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/toastr-notifications.service.ts
  frontend/src/app/shared/components/custom-toastr-notification/custom-toastr-notification.component.html
  frontend/src/app/shared/components/custom-toastr-notification/custom-toastr-notification.component.sass
  frontend/src/app/shared/components/custom-toastr-notification/custom-toastr-notification.component.ts
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/configurations/toastr-global-config.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/app/shared/utils/toastr/toastr-animations.ts
  frontend/src/app/shared/utils/toastr/toastr-options.utils.ts
  frontend/src/styles/global.sass
Labels: bug, enhancement

#200 Feature/229-notifications-design
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/ICodeFightService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/INotificationService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/INotitficationSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/NotificationProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/CodeFightService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/NotificationSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/NotificationService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeFight/CodeFightRequestNotificationDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeFight/CodeFightStartDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Friendship/FriendshipPreviewDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/Notifications/NotificationDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/User/BriefUserInfoDto.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/NotificatioinsConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/EntityConfigurations/UserNotificationConfig.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/LeetWarsCoreContext.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Context/ModelBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/Notification.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Entities/UserNotification.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Enums/TypeNotifications.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230928141139_CreateNotifications.Designer.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/20230928141139_CreateNotifications.cs
  backend/LeetWars.Core/LeetWars.Core.DAL/Migrations/LeetWarsCoreContextModelSnapshot.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/CodeFightController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/NotificationsController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/Interfaces/INotificationsHubClient.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Program.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/NotificationConsumerService.cs
  frontend/src/app/core/services/notification-storage.service.ts
  frontend/src/app/core/services/notification.service.ts
  frontend/src/app/shared/animations/fade-in-out.animation.ts
  frontend/src/app/shared/animations/long-fade-in.animation.ts
  frontend/src/app/shared/components/custom-toastr-notification/custom-toastr-notification.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/components/notifications/notifications.component.sass
  frontend/src/app/shared/components/notifications/notifications.component.ts
  frontend/src/app/shared/models/notifications/notifications.ts
  frontend/src/app/shared/models/user/brief-user.ts
Labels: enhancement

#202 Feature/199-modal-submit-result
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Interfaces/ICodeAnalysisService.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Models/CodeRunRequest.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Models/CodeSubmitResult.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Program.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Services/CodeAnalysisHttpClient.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/Services/ConsumeMessages.cs
  backend/LeetWars.Builder/LeetWars.Builder.WebAPI/appsettings.json
  backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/CompletionService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeAnalysis/CodeRequestAnalysisDto.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/CodeRunRequest/CodeRunRequestDto.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Helpers/JsonConvertingHelper.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Hubs/Interfaces/ICodeDisplayingHubClient.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Models/CodeSubmitResult.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/CodeMessageConsumerService.cs
  frontend/src/app/core/hubs/code-displaying-hub.service.ts
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/user/user.module.ts
  frontend/src/app/shared/components/pie-chart/data.ts
  frontend/src/app/shared/components/pie-chart/pie-chart.component.html
  frontend/src/app/shared/components/pie-chart/pie-chart.component.sass
  frontend/src/app/shared/components/pie-chart/pie-chart.component.ts
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.html
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.sass
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.ts
  frontend/src/app/shared/constants/color-constants.ts
  frontend/src/app/shared/models/code-analysis/code-analysis-request.ts
  frontend/src/app/shared/models/code-analysis/code-analysis-result.ts
  frontend/src/app/shared/models/code-run/code-run-request.ts
  frontend/src/app/shared/models/code-run/code-submit-result.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/color-variables.sass
Labels: enhancement

#208 Bug/94 102 editor and profile pages
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Validators/Sample/NewSampleDtoValidator.cs
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.sass
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.ts
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/modules/user/badge/badge.component.html
  frontend/src/app/modules/user/badge/badge.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.html
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.ts
  frontend/src/styles/global.sass
Labels: bug, enhancement

#210 Bugfix/modal on create challenge
  frontend/src/app/core/guards/unsaved-changes.guard.ts
  frontend/src/app/core/services/code-run.service.ts
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.sass
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.utils.ts
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.sass
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/user/badge/badge.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
Labels: bug

#216 Improvements/small changes
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/SampleProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/UserProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/NotificationService.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/NotificationConsumerService.cs
  frontend/src/app/core/guards/codefight.guard.ts
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.utils.ts
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/leader/leader-board/leader-board.component.ts
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.ts
  frontend/src/app/shared/components/confirmation-modal/confirmation-modal.component.html
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/components/notifications/notifications.component.ts
  frontend/src/app/shared/models/user/brief-user.ts
Labels: bug, enhancement

#206 added markdown preview
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/interceptors/error.interceptor.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.sass
  frontend/src/app/modules/user/user-profile/user-profile.component.sass
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/shared/components/notifications/notifications.component.html
  frontend/src/app/shared/components/notifications/notifications.component.ts
  frontend/src/styles/screen-sizes-variables.sass
Labels: bug

#221 Improvement/code fight modals
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/NotificationConsumerService.cs
  frontend/src/app/core/guards/codefight.guard.ts
  frontend/src/app/core/hubs/notifications-hub.service.ts
  frontend/src/app/core/services/toastr-notifications.service.ts
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.html
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/app/shared/components/custom-toastr-notification/custom-toastr-notification.component.html
  frontend/src/app/shared/components/pie-chart/pie-chart.component.html
  frontend/src/app/shared/utils/toastr/toastr-code-fight-options.ts
  frontend/src/styles/global.sass
Labels: bug, enhancement

#224 reworked styles, created btn component
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.html
  frontend/src/app/modules/user/user-info-editor/user-info-editor.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
  frontend/src/app/shared/components/link-profile-button/link-profile-button.component.html
  frontend/src/app/shared/components/link-profile-button/link-profile-button.component.sass
  frontend/src/app/shared/components/link-profile-button/link-profile-button.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
Labels: bug, enhancement

#225 bugfix/88-full-screen-icon
  frontend/src/app/modules/challenges/challenges-test-page/challenges-test-page.component.ts
Labels: bug

#227 bugfix/136-modal-transparency
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.sass
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.sass
Labels: bug

#229 reworked prefferences, leaderboard
  frontend/src/app/modules/leader/leader-board/leader-board.component.html
  frontend/src/app/modules/leader/leader-board/leader-board.component.sass
  frontend/src/app/modules/user/user-preferences/user-preferences.component.html
  frontend/src/app/modules/user/user-preferences/user-preferences.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
Labels: bug, enhancement

#228 Improvemets/22-25-scroll-feedback
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/INotificationService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/ChallengeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/NotificationService.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/NotificationsController.cs
  frontend/src/app/core/services/notification-storage.service.ts
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
Labels: enhancement

#230 Improvement/23 33 loader and submition
  backend/LeetWars.CodeAnalyzer/LeetWars.CodeAnalyzer.WebAPI/Services/AnalyzeCodeService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IUserService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/ChallengeProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/MappingProfiles/UserProfile.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/UserService.cs
  backend/LeetWars.Core/LeetWars.Core.Common/DTO/UserSolution/NewUserSolutionDto.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Controllers/UsersController.cs
  frontend/src/app/core/services/user.service.ts
  frontend/src/app/modules/challenges/challenge-creation/challenge-creation.component.ts
  frontend/src/app/modules/challenges/online-editor-page/online-editor-page.component.ts
  frontend/src/app/shared/components/loading-spinner/loading-spinner.component.sass
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.html
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.sass
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.ts
  frontend/src/app/shared/models/profile/user-solution.ts
  frontend/src/app/shared/models/user/new-user-solution.ts
  frontend/src/app/shared/models/user/user-solution.ts
  frontend/src/app/shared/models/user/user-solutions-groupedby-skill-level.ts
Labels: enhancement

#231 fixed modal background
  frontend/src/app/shared/components/solution-submit-modal/solution-submit-modal.component.sass
Labels: bug
