Repository BinaryStudioAcademy/bsa-2023-leetwars, pull requests merged in 2023-08, with the labels that each got.

#5 Feature/10, auto migration flow
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ApplicationBuilderExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
Labels: enhancement

#8 Feature/13 - add generic http client
  frontend/src/app/core/services/http-internal.service.ts
Labels: enhancement

#9 Feature/17 - Icons library
  frontend/package.json
  frontend/src/app/shared/shared.module.ts
  frontend/yarn.lock
Labels: enhancement

#4 Feature/2 - create database schema
  .gitignore
  README.md
Labels: documentation

#7 Feature/14 auth service for client
  frontend/src/app/core/guards/auth.guard.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/shared/models/fake-user.ts
Labels: enhancement

#6 Feature/16 toastr notifications
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/core/services/toastr-notifications.service.ts
  frontend/src/polyfills.ts
  frontend/src/styles/global.sass
  frontend/src/styles/index.sass
  frontend/yarn.lock
Labels: enhancement

#19 Add dropdown select
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/color-variables.sass
Labels: enhancement

#14 Feature/5 log in page
  frontend/angular.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/log-in/log-in-page/log-in-page.component.html
  frontend/src/app/modules/log-in/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/log-in/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/log-in/log-in-routing.module.ts
  frontend/src/app/modules/log-in/log-in.module.ts
  frontend/src/polyfills.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/fonts.sass
Labels: enhancement

#16 Feature/26-builder service
  .github/workflows/сontinuous-integration.yml
  README.md
  backend/LeetWars.All.sln
  backend/LeetWars.Builder/Dockerfile
  backend/LeetWars.Builder/LeetWars.Builder.csproj
  backend/LeetWars.Builder/Program.cs
  backend/LeetWars.Builder/Properties/launchSettings.json
  backend/LeetWars.Builder/appsettings.Development.json
  backend/LeetWars.Builder/appsettings.json
  docker-compose.apps.yml
Labels: enhancement

#15 Feature/18 sign up page
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/log-in-routing.module.ts
  frontend/src/app/modules/login/log-in.module.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
  frontend/src/styles/screen-sizes-variables.sass
Labels: enhancement

#26 Feature/41-charts-library
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/yarn.lock
Labels: enhancement

#27 Feature/24 suggested challenge component
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/fonts.sass
Labels: enhancement

#28 Feature/6 main page
  frontend/src/app/app.component.sass
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/app/shared/components/challenge/challenge.component.html
  frontend/src/app/shared/components/challenge/challenge.component.sass
  frontend/src/app/shared/components/challenge/challenge.component.ts
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/filtering-section/filtering-section.component.html
  frontend/src/app/shared/components/filtering-section/filtering-section.component.sass
  frontend/src/app/shared/components/filtering-section/filtering-section.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/images/html.png
  frontend/src/assets/images/js.png
  frontend/src/assets/images/ruby.png
  frontend/src/styles/bootstrap-variables.sass
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
Labels: enhancement

#35 Feature/44 replace all inputs with custom
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/login/log-in-page/log-in-page.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.ts
  frontend/src/app/shared/components/filtering-section/filtering-section.component.html
Labels: enhancement

#29 Feature/36-monaco-editor
  frontend/angular.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/shared/components/code-editor/code-editor.component.html
  frontend/src/app/shared/components/code-editor/code-editor.component.sass
  frontend/src/app/shared/components/code-editor/code-editor.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/yarn.lock
Labels: enhancement

#33 Feature/32 profile page main info
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.html
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.sass
  frontend/src/app/modules/user/profile-page-main-info/profile-page-main-info.component.ts
  frontend/src/app/modules/user/user-routing.module.ts
  frontend/src/app/modules/user/user.module.ts
  frontend/src/app/shared/components/challenge/challenge.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/filtering-section/filtering-section.component.sass
  frontend/src/app/shared/components/not-found/not-found.component.sass
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.sass
  frontend/src/assets/images/default-profile-img.jpg
  frontend/src/styles/color-variables.sass
  frontend/src/styles/global.sass
Labels: enhancement

#41 Feature/51 queue core&notifier
  backend/LeetWars.Core/LeetWars.Core.BLL/Interfaces/IMessageSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.BLL/LeetWars.Core.BLL.csproj
  backend/LeetWars.Core/LeetWars.Core.BLL/Services/MessageSenderService.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/LeetWars.Core.WebAPI.csproj
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Program.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Properties/launchSettings.json
  backend/LeetWars.Core/LeetWars.Core.WebAPI/appsettings.json
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/LeetWars.Notifier.WebAPI.csproj
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Program.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/Services/MessageConsumerService.cs
  backend/LeetWars.Notifier/LeetWars.Notifier.WebAPI/appsettings.json
Labels: enhancement

#42 feature/52-suggested-challenge-component-filters
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.ts
Labels: enhancement

#46 Feature/59 steps of progress
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/shared/components/steps-of-progress/steps-of-progress.component.html
  frontend/src/app/shared/components/steps-of-progress/steps-of-progress.component.sass
  frontend/src/app/shared/components/steps-of-progress/steps-of-progress.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/screen-sizes-variables.sass
Labels: enhancement

#39 Feature/50 queue core & builder
  backend/LeetWars.Builder/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Builder/LeetWars.Builder.csproj
  backend/LeetWars.Builder/Program.cs
  backend/LeetWars.Builder/Services/ConsumeMessages.cs
  backend/LeetWars.Builder/appsettings.json
  backend/LeetWars.Core/LeetWars.Core.BLL/LeetWars.Core.BLL.csproj
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/LeetWars.Core.WebAPI.csproj
Labels: enhancement

#49 fixed rabbitmq config
  backend/LeetWars.Builder/Extensions/ServiceCollectionExtensions.cs
  backend/LeetWars.Builder/appsettings.json
  backend/LeetWars.Core/LeetWars.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/LeetWars.Core/LeetWars.Core.WebAPI/appsettings.json
Labels: bug

#52 Feature/58 name and description page
  frontend/angular.json
  frontend/package.json
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
  frontend/src/app/shared/components/editor-question/editor-question.component.html
  frontend/src/app/shared/components/editor-question/editor-question.component.sass
  frontend/src/app/shared/components/editor-question/editor-question.component.ts
  frontend/src/app/shared/enums/category-type.ts
  frontend/src/app/shared/enums/tab-type.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/assets/images/categories-icons/abasus-icon.png
  frontend/src/assets/images/categories-icons/bookmark-icon.png
  frontend/src/assets/images/categories-icons/bug-icon.png
  frontend/src/assets/images/categories-icons/cone-icon.png
  frontend/src/assets/images/categories-icons/rubik-icon.png
  frontend/src/styles/color-variables.sass
  frontend/yarn.lock
Labels: enhancement

#55 bug/3 main page design
  frontend/src/app/shared/components/challenge/challenge.component.sass
  frontend/src/app/shared/components/filtering-section/filtering-section.component.html
  frontend/src/app/shared/components/filtering-section/filtering-section.component.sass
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.sass
  frontend/src/styles/bootstrap-variables.sass
Labels: bug

#45 Feature/47 file build via docker
  backend/LeetWars.Builder/Interfaces/ISolutionRunnerService.cs
  backend/LeetWars.Builder/LeetWars.Builder.csproj
  backend/LeetWars.Builder/Program.cs
  backend/LeetWars.Builder/RunnerDefaults/CSharp/CSharpRunner/CSharpBuildAndRun.sh
  backend/LeetWars.Builder/RunnerDefaults/CSharp/CSharpRunner/CSharpRunner.csproj
  backend/LeetWars.Builder/RunnerDefaults/CSharp/Dockerfile
  backend/LeetWars.Builder/RunnerDefaults/CSharp/Program.txt
  backend/LeetWars.Builder/RunnerDefaults/DefaultRunnerImageNames.cs
  backend/LeetWars.Builder/RunnerDefaults/JS/Dockerfile
  backend/LeetWars.Builder/RunnerDefaults/JS/JSRunner/JSBuildAndRun.sh
  backend/LeetWars.Builder/RunnerDefaults/JS/app.txt
  backend/LeetWars.Builder/Services/SolutionRunnerService.cs
  docker-compose.apps.prod.yml
  docker-compose.apps.yml
  docker-compose.code-runners.yml
Labels: enhancement

#60 bugfix/10-removed white background on autocomplete
  frontend/src/styles/global.sass
Labels: bug

#62 Bug/2 design login page
  frontend/src/app/modules/login/log-in-page/log-in-page.component.html
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.ts
Labels: bug

#59 Bug/3 main page design
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.sass
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.ts
  frontend/src/styles/color-variables.sass
Labels: bug

#58 [BUG#4] [Main page link] The page is accessible to an unauthorized user
  frontend/src/app/app-routing.module.ts
  frontend/src/app/core/guards/auth.guard.ts
Labels: bug

#57 Add hover on buttons
  frontend/src/app/shared/components/suggested-challenge/suggested-challenge.component.sass
Labels: bug

#65 Feature/73 modules structure
  frontend/src/app/modules/challenges/challenges-routing.module.ts
  frontend/src/app/modules/challenges/challenges.module.ts
  frontend/src/app/modules/challenges/editor-question/editor-question.component.html
  frontend/src/app/modules/challenges/editor-question/editor-question.component.sass
  frontend/src/app/modules/challenges/editor-question/editor-question.component.ts
  frontend/src/app/modules/challenges/steps-of-progress/steps-of-progress.component.html
  frontend/src/app/modules/challenges/steps-of-progress/steps-of-progress.component.sass
  frontend/src/app/modules/challenges/steps-of-progress/steps-of-progress.component.ts
  frontend/src/app/modules/main/challenge/challenge.component.html
  frontend/src/app/modules/main/challenge/challenge.component.sass
  frontend/src/app/modules/main/challenge/challenge.component.ts
  frontend/src/app/modules/main/filtering-section/filtering-section.component.html
  frontend/src/app/modules/main/filtering-section/filtering-section.component.sass
  frontend/src/app/modules/main/filtering-section/filtering-section.component.ts
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#44 [BUG#1] [Header] header fix
  frontend/src/app/app.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/login/sign-up-page/sign-up.component.html
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.sass
Labels: bug

#68 Feature/61 landing page
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/landing/landing-page/landing-page.component.ts
  frontend/src/assets/images/landing-page/clock.svg
  frontend/src/assets/images/landing-page/cursor.svg
  frontend/src/assets/images/landing-page/fun-programming1.svg
  frontend/src/assets/images/landing-page/fun-programming2.svg
  frontend/src/assets/images/landing-page/fun-programming3.svg
  frontend/src/assets/images/landing-page/how-it-works1.svg
  frontend/src/assets/images/landing-page/how-it-works2.svg
  frontend/src/assets/images/landing-page/how-it-works3.svg
  frontend/src/assets/images/landing-page/landing-page-stepper.svg
  frontend/src/assets/images/landing-page/message.svg
  frontend/src/assets/images/landing-page/reliable1.svg
  frontend/src/assets/images/landing-page/reliable2.svg
  frontend/src/assets/images/landing-page/reliable3.svg
  frontend/src/assets/images/landing-page/unlimited.svg
  frontend/src/styles/color-variables.sass
Labels: enhancement

#54 Feature/52 suggested challenge component filters
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.html
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.html
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.sass
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.ts
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.html
  frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
  frontend/src/assets/images/Group.svg
Labels: enhancement

#72 [IMPROVEMENT#1] [Sign In/Sign Up pages] Links for the redirection must be the same
  frontend/src/app/modules/login/log-in-page/log-in-page.component.sass
  frontend/src/app/modules/login/sign-up-page/sign-up.component.sass
  frontend/src/app/shared/components/custom-input/custom-input.component.sass
Labels: enhancement

#74 added preventDefault
  frontend/src/app/shared/components/custom-input/custom-input.component.html
  frontend/src/app/shared/components/custom-input/custom-input.component.ts
Labels: bug

#69 bug/11 main page after authentication
  frontend/src/app/modules/challenges/editor-question/editor-question.component.ts
  frontend/src/app/modules/login/sign-up-page/sign-up.component.ts
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/suggested-challenge/suggested-challenge.component.sass
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.html
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.sass
  frontend/src/app/shared/components/challenges-dropdown-select/challenges-dropdown-select.component.ts
  frontend/src/styles/global.sass
Labels: bug
